// Generated by npm run build. A waiting worker activates only after old tabs close.
const CACHE_PREFIX = `deutsch-trainer:${self.registration.scope}:`;
const CACHE = `${CACHE_PREFIX}5a6eb4407f81`;
const ASSETS = ["./index.html","./icon.svg","./manifest.webmanifest","./data/topics.json","./data/topics/transport.json","./data/topics/wohnung.json","./src/app.js","./src/content.js","./src/scheduler.js","./src/storage.js","./src/styles.css"];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(async cache => {
    await cache.addAll(ASSETS.map(path => new Request(new URL(path,self.registration.scope),{cache:'reload'})));
  }));
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys=await caches.keys();
    await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX) && key!==CACHE).map(key=>caches.delete(key)));
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if(event.request.method!=='GET' || url.origin!==self.location.origin || !url.href.startsWith(self.registration.scope))return;
  event.respondWith((async () => {
    const cache=await caches.open(CACHE);
    if(event.request.mode==='navigate') return await cache.match(new URL('./index.html',self.registration.scope)) || fetch(event.request);
    return await cache.match(event.request) || fetch(event.request);
  })());
});
